apiVersion: v1
kind: Service
metadata:
  name: ctlac-app-service
spec:
  selector:
    app: ctlac-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31110